name: Run Tests for Workspaces

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  run-tests:
    name: "Run Unit Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download all modules
        run: npm ci

      - name: Create .env file
        run: |
          echo FXSERVER_PATH=$(pwd)/fxserver > .env
          echo VITE_URL='http://localhost:40122' >> .env

      - name: Run Tests
        env:
          CI: true
        run: npm run test --workspaces
